workflows:
  ios-workflow:
    name: iOS Build and TestFlight
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Flutter build ipa
        script: |
          flutter build ipa \
            --release \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        submit_to_testflight: true
