name: pothole
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version: <major>.<minor>.<patch>+<build>
# Increment the build number for every App Store upload
version: 1.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  sizer: ^3.0.5

  # State Management & Routing
  provider: ^6.1.5
  go_router: ^16.0.0

  # Networking & Storage
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5

  # Device Features
  image_picker: ^1.1.2
  camera: ^0.11.2
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  cunning_document_scanner: ^1.3.1
  google_maps_flutter: ^2.12.3
  flutter_image_compress: ^2.4.0

  # Firebase (Push Notifications)
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1

  # Utilities
  intl: ^0.20.2
  pinput: ^5.0.1
  image: ^4.5.4
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/model/
