// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6yLMio7_-WpzOyseNEyyP5d13UHzDPuY',
    appId: '1:582868073653:web:b51f2acc096fd36f7012fc',
    messagingSenderId: '582868073653',
    projectId: 'rudra-d36fe',
    authDomain: 'rudra-d36fe.firebaseapp.com',
    storageBucket: 'rudra-d36fe.firebasestorage.app',
    measurementId: 'G-VTEYXH0SDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf9uiwNLbwX29-E1HA5g01SKVcssF3I_M',
    appId: '1:582868073653:android:35a9e0f23eb0b0f57012fc',
    messagingSenderId: '582868073653',
    projectId: 'rudra-d36fe',
    storageBucket: 'rudra-d36fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE0o_GS_v_ayb7_5Wy3iuWikigpevcwHs',
    appId: '1:582868073653:ios:624d04b285a6fe307012fc',
    messagingSenderId: '582868073653',
    projectId: 'rudra-d36fe',
    storageBucket: 'rudra-d36fe.firebasestorage.app',
    iosBundleId: 'com.pwd.rudra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE0o_GS_v_ayb7_5Wy3iuWikigpevcwHs',
    appId: '1:582868073653:ios:81ce802db9387f567012fc',
    messagingSenderId: '582868073653',
    projectId: 'rudra-d36fe',
    storageBucket: 'rudra-d36fe.firebasestorage.app',
    iosBundleId: 'com.techsavvy.pothole',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6yLMio7_-WpzOyseNEyyP5d13UHzDPuY',
    appId: '1:582868073653:web:248c48539bf92e987012fc',
    messagingSenderId: '582868073653',
    projectId: 'rudra-d36fe',
    authDomain: 'rudra-d36fe.firebaseapp.com',
    storageBucket: 'rudra-d36fe.firebasestorage.app',
    measurementId: 'G-VPH67HZSTK',
  );
}
